"""Bounded, read-only task continuity models and classification service."""

from agent.continuity.models import (
    CONTINUITY_METADATA_SCHEMA_VERSION,
    CONTINUITY_SNAPSHOT_SCHEMA_VERSION,
    MAX_CONTINUITY_TEXT,
    MAX_CONTINUITY_TIMESTAMP,
    MAX_OBJECTIVE_PREVIEW,
    MAX_REASON,
    MAX_RELATED_RUNS,
    ContinuityMetadata,
    PlanProgress,
    RelatedRun,
    TaskContinuityStatus,
)
from agent.continuity.service import (
    REASON_CHECKPOINT_ABSENT,
    REASON_CHECKPOINT_INVALID,
    REASON_CHECKPOINT_INVALID_CONTINUITY,
    REASON_CHECKPOINT_INVALID_TERMINAL_DISPOSITION,
    REASON_CHECKPOINT_RESUMABLE,
    REASON_CHECKPOINT_ROOT_MISSING,
    REASON_HIERARCHICAL_RESUME_UNSUPPORTED,
    REASON_TASK_ALREADY_TERMINAL,
    REASON_TASK_DEFINITION_BINDING_MISSING,
    REASON_TASK_DEFINITION_INCOMPLETE,
    REASON_TASK_PAUSED,
    TaskContinuityService,
    classify_checkpoint_document,
)
from agent.continuity.snapshot import (
    TaskContinuitySnapshot,
    TaskDefinitionRefSummary,
    TaskDefinitionSummary,
)

__all__ = [
    "CONTINUITY_METADATA_SCHEMA_VERSION",
    "CONTINUITY_SNAPSHOT_SCHEMA_VERSION",
    "ContinuityMetadata",
    "classify_checkpoint_document",
    "MAX_CONTINUITY_TEXT",
    "MAX_CONTINUITY_TIMESTAMP",
    "MAX_OBJECTIVE_PREVIEW",
    "MAX_REASON",
    "MAX_RELATED_RUNS",
    "PlanProgress",
    "REASON_CHECKPOINT_ABSENT",
    "REASON_CHECKPOINT_INVALID",
    "REASON_CHECKPOINT_INVALID_CONTINUITY",
    "REASON_CHECKPOINT_INVALID_TERMINAL_DISPOSITION",
    "REASON_CHECKPOINT_RESUMABLE",
    "REASON_CHECKPOINT_ROOT_MISSING",
    "REASON_HIERARCHICAL_RESUME_UNSUPPORTED",
    "REASON_TASK_ALREADY_TERMINAL",
    "REASON_TASK_DEFINITION_BINDING_MISSING",
    "REASON_TASK_DEFINITION_INCOMPLETE",
    "REASON_TASK_PAUSED",
    "RelatedRun",
    "TaskContinuityService",
    "TaskContinuitySnapshot",
    "TaskContinuityStatus",
    "TaskDefinitionRefSummary",
    "TaskDefinitionSummary",
]
